; ============================================================
; Teclas ASCII
; ============================================================

KEY_ENTER       equ 13
KEY_ESCAPE      equ 27
KEY_SPACE       equ 32

KEY_Q_LOWER     equ 'q'
KEY_Q_UPPER     equ 'Q'

KEY_M_LOWER     equ 'm'
KEY_M_UPPER     equ 'M'

KEY_R_LOWER     equ 'r'
KEY_R_UPPER     equ 'R'

KEY_A_LOWER     equ 'a'
KEY_A_UPPER     equ 'A'

KEY_C_LOWER     equ 'c'
KEY_C_UPPER     equ 'C'


; ============================================================
; Modos
; ============================================================

MODE_CLOCK      equ 0
MODE_STOPWATCH  equ 1


; ============================================================
; Posiciones de interfaz
; ============================================================

CLOCK_ROW       equ 10
CLOCK_COLUMN    equ 26

STOPWATCH_ROW       equ 10
STOPWATCH_COLUMN    equ 26

STOPWATCH_STATUS_ROW       equ 11
STOPWATCH_STATUS_COLUMN    equ 21

; ============================================================
; Alarma
; ============================================================

ALARM_INFO_ROW          equ 12
ALARM_INFO_COLUMN       equ 17

ALARM_ALERT_ROW         equ 4
ALARM_ALERT_COLUMN      equ 23

ALARM_INPUT_ROW         equ 10
ALARM_INPUT_COLUMN      equ 27

KEY_BACKSPACE           equ 8
